apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:nginx.ingress.kubernetes.io/rewrite-target: /
  name: sample-ingress
spec:
  rules:
  - host: fuck.local
    http:
      paths:
      - backend:
          serviceName: sample-svc
          servicePort: 3000
        path: /
