apiVersion: v1
kind: Pod
metadata: 
  name: sample-pod
  labels:
    app: sample
spec:
  containers:
  - image: dreamcatchernick/nicktest
    name: test-nodejs
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
